version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      
  app1:
    image: node:lts-alpine
    container_name: app1
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    volumes:
      - ./microservices/app1:/app
    restart: always
    command: sh -c "cd /app && npm install --also-dev && npm run dev"

  app2:
      image: node:lts-alpine
      container_name: app2
      ports:
        - "8081:8081"
      depends_on:
        - rabbitmq
      volumes:
        - ./microservices/app2:/app
      restart: always
      command: sh -c "cd /app && npm install --also-dev && npm run dev"