version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  admin-backend:
    image: node:lts-alpine
    container_name: admin-backend
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    volumes:
      - ./adminApp/backend:/app
    restart: always
    command: sh -c "cd /app && npm install --also-dev && npm run dev"

  admin-frontend:
    image: node:lts-alpine
    container_name: admin-frontend
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    volumes:
      - ./adminApp/frontend:/app
    restart: always
    command: sh -c "cd /app && npm install --also-dev && npm start"

  notifyMicroservice:
    image: node:lts-alpine
    container_name: notifyMicroservice
    ports:
      - "9999:9999"
    depends_on:
      - rabbitmq
    volumes:
      - ./microservices/notify:/app
    command: sh -c "cd /app && npm install --also-dev && npm run dev"
